Fix bug in sync_dtd, thanks to freke

diff --git a/etc/portage/postsync.d/sync_dtd b/etc/portage/postsync.d/sync_dtd
--- a/etc/portage/postsync.d/sync_dtd
+++ b/etc/portage/postsync.d/sync_dtd
@@ -9,7 +9,7 @@ einfo "updating dtd directory"
 cd "${PORTDIR}"/metadata || die "could not cd into '${PORTDIR}/metadata'!"
 if [[ -e dtd ]] ; then
 	einfo "dtd dir already exists, updating..."
-	cd glsa || die "could not cd into 'dtd'!"
+	cd dtd || die "could not cd into 'dtd'!"
 	git pull --ff || die "could not pull updates!"
 else
 	einfo "dtd directory does not exist, cloning..."
